import { writeIfChanged } from "./files.js";
import { log } from "./log.js";

export async function reconcileRecyclarr(
  sonarrUrl: string,
  sonarrApiKey: string,
  radarrUrl: string,
  radarrApiKey: string,
): Promise<void> {
  const content = `# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
# Generated by Arrspire's idempotent TypeScript reconciler.
sonarr:
  tv-shows:
    base_url: ${sonarrUrl}
    api_key: ${sonarrApiKey}
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

radarr:
  movies:
    base_url: ${radarrUrl}
    api_key: ${radarrApiKey}
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web
`;
  const changed = await writeIfChanged(
    "/data/recyclarr/recyclarr.yml",
    content,
  );
  log.info("Recyclarr configuration reconciled", { changed });
}
