import { chown } from "node:fs/promises";

import { writeIfChanged } from "./files.js";
import { log } from "./log.js";

export function recyclarrConfigOwnership(): Readonly<{
  path: string;
  uid: number;
  gid: number;
}> {
  return {
    path: "/data/recyclarr/recyclarr.yml",
    uid: 1000,
    gid: 1000,
  };
}

export function recyclarrConfiguration(
  sonarrUrl: string,
  sonarrApiKey: string,
  radarrUrl: string,
  radarrApiKey: string,
): string {
  return `# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
# Generated by Arrspire's idempotent TypeScript reconciler.
sonarr:
  tv-shows:
    base_url: ${sonarrUrl}
    api_key: ${sonarrApiKey}
    delete_old_custom_formats: true
    quality_definition:
      type: series
    quality_profiles:
      - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        reset_unmatched_scores:
          enabled: true

radarr:
  movies:
    base_url: ${radarrUrl}
    api_key: ${radarrApiKey}
    delete_old_custom_formats: true
    quality_definition:
      type: movie
    quality_profiles:
      - trash_id: d1d67249d3890e49bc12e275d989a7e9 # HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
`;
}

export async function reconcileRecyclarr(
  sonarrUrl: string,
  sonarrApiKey: string,
  radarrUrl: string,
  radarrApiKey: string,
): Promise<void> {
  const content = recyclarrConfiguration(
    sonarrUrl,
    sonarrApiKey,
    radarrUrl,
    radarrApiKey,
  );
  const changed = await writeIfChanged(
    "/data/recyclarr/recyclarr.yml",
    content,
  );
  const ownership = recyclarrConfigOwnership();
  await chown(ownership.path, ownership.uid, ownership.gid);
  log.info("Recyclarr configuration reconciled", { changed });
}
